// GENERATED by scripts/build-step-images-map.mjs — do not edit by hand.
// Add or remove files in public/steps/ and re-run the script.
//
// Keyed as `<exerciseId>:<stepIndex>` (0-based). Any entry here wins over the
// generated SVG pose illustration; anything absent falls back to SVG.
export const stepImages: Record<string, string> = {

};

export function getStepImage(exerciseId: string, stepIndex: number): string | undefined {
  return stepImages[`${exerciseId}:${stepIndex}`];
}
